name: OPA Conftest Policy Check

on:
  pull_request:
    paths:
      - "infra/**"
      - "policies/**"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  policy-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::824090260951:role/github-sruthishtechnologies-role
          aws-region: ap-south-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan.binary

      - name: Convert plan to JSON
        working-directory: infra
        run: terraform show -json tfplan.binary > plan.json

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.56.0/conftest_0.56.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.56.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Run OPA Conftest Policies
        run: |
          conftest test infra/plan.json \
            --policy policies/terraform

      - name: Check Exception Label
        id: exception
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'policy-exception-approved') }}" == "true" ]]; then
            echo "approved=true" >> $GITHUB_OUTPUT
          else
            echo "approved=false" >> $GITHUB_OUTPUT
          fi
